// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric-go/masterfabric/graph/scalar"
)

type AuditEntry struct {
	ID           uuid.UUID   `json:"id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resourceType"`
	ResourceID   string      `json:"resourceId"`
	UserID       *uuid.UUID  `json:"userId,omitempty"`
	Metadata     scalar.JSON `json:"metadata,omitempty"`
	IPAddress    *string     `json:"ipAddress,omitempty"`
	CreatedAt    time.Time   `json:"createdAt"`
}

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	// Rotasyonlu yenileme zincirinin bu andaki halkası.
	RefreshToken   string        `json:"refreshToken"`
	ExpiresAt      time.Time     `json:"expiresAt"`
	OrganizationID uuid.UUID     `json:"organizationId"`
	User           *User         `json:"user"`
	Device         *PairedDevice `json:"device,omitempty"`
}

type Character struct {
	ID        uuid.UUID      `json:"id"`
	LineageID uuid.UUID      `json:"lineageId"`
	Version   int            `json:"version"`
	Status    DocumentStatus `json:"status"`
	Name      string         `json:"name"`
	// Karakterin kim olduğu. Sistem prompt'una olduğu gibi girer.
	Persona       string     `json:"persona"`
	BehaviorRules []string   `json:"behaviorRules"`
	Difficulty    Difficulty `json:"difficulty"`
	// Karakterin sakladığı bilgiler. Çalışan doğru soruyu sorarsa açılır;
	// prompt'a 'bunları kendiliğinden söyleme' talimatıyla girer.
	HiddenFacts []string   `json:"hiddenFacts"`
	CreatedAt   time.Time  `json:"createdAt"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
}

type CharacterInput struct {
	Name          string     `json:"name"`
	Persona       string     `json:"persona"`
	BehaviorRules []string   `json:"behaviorRules"`
	Difficulty    Difficulty `json:"difficulty"`
	HiddenFacts   []string   `json:"hiddenFacts,omitempty"`
}

type Criterion struct {
	Key         string  `json:"key"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Weight      float64 `json:"weight"`
	MaxPoints   float64 `json:"maxPoints"`
	// Zorunlu kriter. Düşerse toplam puan ne olursa olsun sonuç KALDI.
	Mandatory bool `json:"mandatory"`
	// Karaktere talimat olarak verilen tuzak. KVKK senaryolarında karakter bunu
	// kullanarak çalışandan başkasının kişisel verisini istemeye çalışır.
	Trap *string `json:"trap,omitempty"`
}

type CriterionInput struct {
	Key         string  `json:"key"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Weight      float64 `json:"weight"`
	MaxPoints   float64 `json:"maxPoints"`
	Mandatory   bool    `json:"mandatory"`
	Trap        *string `json:"trap,omitempty"`
}

type CriterionScore struct {
	CriterionKey string  `json:"criterionKey"`
	Title        string  `json:"title"`
	Weight       float64 `json:"weight"`
	Mandatory    bool    `json:"mandatory"`
	Points       float64 `json:"points"`
	MaxPoints    float64 `json:"maxPoints"`
	Rationale    string  `json:"rationale"`
	// Modelin gerekçe olarak gösterdiği transkript alıntısı.
	Quote string `json:"quote"`
	// Alıntının geldiği konuşma sırası.
	TurnIndex *int `json:"turnIndex,omitempty"`
	// Alıntının o sıranın metninde gerçekten bulunup bulunmadığı. Uydurma alıntı
	// ürünün güvenilirliğini bitirir; sessizce geçilmez.
	QuoteVerified bool `json:"quoteVerified"`
}

// KVKK erişim hakkının karşılığı: kullanıcıya ait her şey tek belgede.
type DataExport struct {
	ExportedAt time.Time     `json:"exportedAt"`
	User       *User         `json:"user"`
	Devices    []*Device     `json:"devices"`
	Sessions   []*Session    `json:"sessions"`
	AuditLog   []*AuditEntry `json:"auditLog"`
	// Ham JSON gövdesi; istemci bunu dosya olarak indirir.
	Document scalar.JSON `json:"document"`
}

type DeletionStatus struct {
	RequestedAt *time.Time `json:"requestedAt,omitempty"`
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`
	// Geri alınabilir mi. Kalıcı silme çalıştıktan sonra false.
	Cancellable bool `json:"cancellable"`
}

type Device struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	Platform   DevicePlatform `json:"platform"`
	LastSeenAt time.Time      `json:"lastSeenAt"`
	RevokedAt  *time.Time     `json:"revokedAt,omitempty"`
	// Anahtar çifti kayıtlı mı. Değilse cihaz yalnızca eski parmak izi eşleşmesiyle tanınır.
	HasPublicKey bool      `json:"hasPublicKey"`
	CreatedAt    time.Time `json:"createdAt"`
}

// Cihazın imzalaması gereken tek kullanımlık meydan okuma.
type DeviceChallenge struct {
	Challenge string    `json:"challenge"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type DeviceChallengeInput struct {
	Email       string `json:"email"`
	Fingerprint string `json:"fingerprint"`
}

type DeviceInput struct {
	// Makinenin parmak izi. Sunucuda hash'lenerek saklanır; düz metin tutulmaz.
	Fingerprint string  `json:"fingerprint"`
	Name        *string `json:"name,omitempty"`
	Platform    *string `json:"platform,omitempty"`
	// Cihazın ürettiği açık anahtar (base64, Ed25519). Özel anahtar işletim
	// sisteminin güvenli deposunda kalır ve sunucuya hiç gelmez.
	PublicKey *string `json:"publicKey,omitempty"`
}

// Bir oturumdan, oynandığı belgenin tam sürümüne işaret eden bağ.
//
// Yalnızca soy kimliğini tutan bir referans, sonradan yayınlanan sürüme sessizce
// kayardı; sertifikasyon iddiasının dayandığı şey tam olarak bunun olmamasıdır.
type DocumentRef struct {
	LineageID uuid.UUID `json:"lineageId"`
	VersionID uuid.UUID `json:"versionId"`
	Version   int       `json:"version"`
}

// Profili canlıya almadan tek seferlik deneme sonucu.
type LLMProbeResult struct {
	ProfileID    uuid.UUID `json:"profileId"`
	Model        string    `json:"model"`
	Output       string    `json:"output"`
	LatencyMs    int       `json:"latencyMs"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	CostUsd      float64   `json:"costUsd"`
	Error        *string   `json:"error,omitempty"`
}

type LLMProfile struct {
	ID        uuid.UUID      `json:"id"`
	LineageID uuid.UUID      `json:"lineageId"`
	Version   int            `json:"version"`
	Status    DocumentStatus `json:"status"`
	Tier      LLMTier        `json:"tier"`
	Provider  string         `json:"provider"`
	BaseURL   string         `json:"baseUrl"`
	// Model kimliği. Koda gömülmez; çalışma anında değiştirilebilir.
	Model       string  `json:"model"`
	Temperature float64 `json:"temperature"`
	TopP        float64 `json:"topP"`
	MaxTokens   int     `json:"maxTokens"`
	// Yöneticinin eklediği sistem prompt eki. Sabit guardrail metnini ezemez:
	// guardrail prompt derlenirken her zaman en başa gelir.
	SystemPromptSuffix string    `json:"systemPromptSuffix"`
	InputCostPer1k     float64   `json:"inputCostPer1K"`
	OutputCostPer1k    float64   `json:"outputCostPer1K"`
	CreatedAt          time.Time `json:"createdAt"`
}

type LLMProfileInput struct {
	Tier               LLMTier `json:"tier"`
	Provider           string  `json:"provider"`
	BaseURL            string  `json:"baseUrl"`
	Model              string  `json:"model"`
	Temperature        float64 `json:"temperature"`
	TopP               float64 `json:"topP"`
	MaxTokens          int     `json:"maxTokens"`
	SystemPromptSuffix *string `json:"systemPromptSuffix,omitempty"`
	InputCostPer1k     float64 `json:"inputCostPer1K"`
	OutputCostPer1k    float64 `json:"outputCostPer1K"`
}

type Mutation struct {
}

type OverrideScoreInput struct {
	ScoreID uuid.UUID `json:"scoreId"`
	Total   float64   `json:"total"`
	Passed  bool      `json:"passed"`
	Reason  string    `json:"reason"`
}

type PairedDevice struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Platform DevicePlatform `json:"platform"`
	// Bu makineden ilk giriş. Yeni cihaz bildirimini tetikleyen de budur.
	IsNew bool `json:"isNew"`
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterInput struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type RegisterPayload struct {
	Registered         bool   `json:"registered"`
	Email              string `json:"email"`
	ExpiresInSeconds   int    `json:"expiresInSeconds"`
	ResendAfterSeconds int    `json:"resendAfterSeconds"`
}

type RequestEmailVerificationCodeInput struct {
	Email string `json:"email"`
}

type RequestEmailVerificationCodePayload struct {
	// İstek kabul edildi; hesap varlığı veya doğrulama durumu hakkında sinyal taşımaz.
	Sent               bool `json:"sent"`
	ExpiresInSeconds   int  `json:"expiresInSeconds"`
	ResendAfterSeconds int  `json:"resendAfterSeconds"`
}

type RequestLoginCodeInput struct {
	Email string `json:"email"`
}

// Kod isteme yanıtı.
//
// Adresin bir hesaba ait olup olmadığına dair hiçbir sinyal taşımaz: kayıtlı
// adres, bilinmeyen adres ve limitlenmiş adres için aynı gövde döner.
type RequestLoginCodePayload struct {
	// Her zaman true. 'İstek kabul edildi' demektir, 'e-posta çıktı' değil.
	Sent               bool `json:"sent"`
	ExpiresInSeconds   int  `json:"expiresInSeconds"`
	ResendAfterSeconds int  `json:"resendAfterSeconds"`
}

type RoutingRecord struct {
	ID        uuid.UUID  `json:"id"`
	SessionID *uuid.UUID `json:"sessionId,omitempty"`
	Tier      LLMTier    `json:"tier"`
	// Bu kademeyi seçen kural.
	Rule         string    `json:"rule"`
	Model        string    `json:"model"`
	LatencyMs    int       `json:"latencyMs"`
	InputTokens  int       `json:"inputTokens"`
	OutputTokens int       `json:"outputTokens"`
	CostUsd      float64   `json:"costUsd"`
	Success      bool      `json:"success"`
	Error        *string   `json:"error,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

// Otomatik dağılımın kanıtı.
//
// Grafik çizilebilir veri üretmeyen bir dağılım iddiası doğrulanamaz; bu sorgu
// o veriyi üretir.
type RoutingStats struct {
	PerTier []*TierStats `json:"perTier"`
	// Hızlı kademenin devresi açıkken güçlüye kayan çağrı sayısı.
	FailoverCount int     `json:"failoverCount"`
	TotalCostUsd  float64 `json:"totalCostUsd"`
	// Her çağrı güçlü kademeye gitseydi oluşacak maliyet.
	AllStrongCostUsd float64 `json:"allStrongCostUsd"`
	SavingsPercent   float64 `json:"savingsPercent"`
}

type Rubric struct {
	ID          uuid.UUID      `json:"id"`
	LineageID   uuid.UUID      `json:"lineageId"`
	Version     int            `json:"version"`
	Status      DocumentStatus `json:"status"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	// Geçme eşiği, toplam puanın yüzdesi olarak.
	PassThreshold float64      `json:"passThreshold"`
	Criteria      []*Criterion `json:"criteria"`
	CreatedAt     time.Time    `json:"createdAt"`
	PublishedAt   *time.Time   `json:"publishedAt,omitempty"`
}

type RubricInput struct {
	Name          string            `json:"name"`
	Description   string            `json:"description"`
	PassThreshold float64           `json:"passThreshold"`
	Criteria      []*CriterionInput `json:"criteria"`
}

type Scenario struct {
	ID           uuid.UUID      `json:"id"`
	LineageID    uuid.UUID      `json:"lineageId"`
	Version      int            `json:"version"`
	Status       DocumentStatus `json:"status"`
	Title        string         `json:"title"`
	Context      string         `json:"context"`
	Objective    string         `json:"objective"`
	CharacterRef *DocumentRef   `json:"characterRef"`
	RubricRef    *DocumentRef   `json:"rubricRef"`
	MaxTurns     int            `json:"maxTurns"`
	CreatedAt    time.Time      `json:"createdAt"`
	PublishedAt  *time.Time     `json:"publishedAt,omitempty"`
}

type ScenarioInput struct {
	Title              string    `json:"title"`
	Context            string    `json:"context"`
	Objective          string    `json:"objective"`
	CharacterLineageID uuid.UUID `json:"characterLineageId"`
	RubricLineageID    uuid.UUID `json:"rubricLineageId"`
	MaxTurns           int       `json:"maxTurns"`
}

type Score struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"sessionId"`
	Total     float64   `json:"total"`
	MaxTotal  float64   `json:"maxTotal"`
	Passed    bool      `json:"passed"`
	// Zorunlu bir kriter düştüyse hangisi olduğu. Toplam puan yeterli olsa bile
	// sonuç KALDI'dır ve nedeni buradadır.
	FailedMandatoryKeys []string          `json:"failedMandatoryKeys"`
	Criteria            []*CriterionScore `json:"criteria"`
	// Puanı üreten model kimliği.
	Model string `json:"model"`
	// Skor ezme kaydı. Yetkisiz kullanıcıda null döner; çalışan sonuçları
	// göremediği için bu alan yalnızca yetkili yönetici sorgularında anlamlıdır.
	Override  *ScoreOverride `json:"override,omitempty"`
	CreatedAt time.Time      `json:"createdAt"`
}

type ScoreOverride struct {
	OverriddenBy   uuid.UUID `json:"overriddenBy"`
	Reason         string    `json:"reason"`
	PreviousTotal  float64   `json:"previousTotal"`
	PreviousPassed bool      `json:"previousPassed"`
	OverriddenAt   time.Time `json:"overriddenAt"`
}

type Session struct {
	ID         uuid.UUID     `json:"id"`
	Status     SessionStatus `json:"status"`
	EmployeeID uuid.UUID     `json:"employeeId"`
	// Oturum başlarken dondurulan senaryo sürümü. İçerik sonradan değişse bile
	// oturum kendi sürümüyle puanlanır.
	Scenario  *DocumentRef `json:"scenario"`
	Rubric    *DocumentRef `json:"rubric"`
	Character *DocumentRef `json:"character"`
	Turns     []*Turn      `json:"turns"`
	// Sonuç yalnızca puan okuma yetkisi olan kurum yöneticilerine açılır.
	Score     *Score     `json:"score,omitempty"`
	StartedAt time.Time  `json:"startedAt"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
}

// Oturum olayları için tek kanal.
//
// Union yerine etiketli tek tip kullanılıyor: Next.js ve Electron istemcileri
// şemadan kod üretiyor, ve etiketli tip her iki üreticide de tek bir switch'e
// dönüşürken union her istemcide ayrı tip guard'ları gerektirir.
type SessionEvent struct {
	SessionID uuid.UUID        `json:"sessionId"`
	Type      SessionEventType `json:"type"`
	// TRANSCRIPT_CHUNK ve CHARACTER_REPLY için metin.
	Text *string `json:"text,omitempty"`
	// CHARACTER_REPLY için konuşma sırası.
	Turn *Turn `json:"turn,omitempty"`
	// RUBRIC_SIGNAL için tetiklenen kriter anahtarları.
	Signals []string `json:"signals,omitempty"`
	// SCORING_PROGRESS için 0-100 arası ilerleme.
	Progress *int `json:"progress,omitempty"`
	// SCORE_READY için tamamlanmış puan; yalnızca sonuç okuma yetkisi olan yöneticilere iletilir.
	Score      *Score    `json:"score,omitempty"`
	OccurredAt time.Time `json:"occurredAt"`
}

type StartSessionInput struct {
	ScenarioLineageID uuid.UUID `json:"scenarioLineageId"`
}

type SubmitTurnInput struct {
	SessionID uuid.UUID `json:"sessionId"`
	// Network retry'larında aynı turn'ü iki kez uygulamamak için istemci anahtarı.
	RequestID *uuid.UUID `json:"requestId,omitempty"`
	Text      string     `json:"text"`
}

type Subscription struct {
}

type TestLLMProfileInput struct {
	ProfileLineageID uuid.UUID `json:"profileLineageId"`
	Prompt           string    `json:"prompt"`
}

type TierStats struct {
	Tier         LLMTier `json:"tier"`
	Calls        int     `json:"calls"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
	CostUsd      float64 `json:"costUsd"`
	InputTokens  int     `json:"inputTokens"`
	OutputTokens int     `json:"outputTokens"`
}

type Turn struct {
	Index int      `json:"index"`
	Role  TurnRole `json:"role"`
	// Transkriptin kendisi: maskelenmemiş orijinal metin. Maskeleme yalnızca
	// LLM'e giden kopyada yapılır, çünkü puanlama doğruluğu orijinal metne bağlı.
	Text string `json:"text"`
	// Bu sırada tetiklenen rubrik kriter anahtarları.
	Signals []string `json:"signals"`
	// LLM'e giden kopyada maskelenen kişisel veri alanı sayısı.
	MaskedFieldCount int       `json:"maskedFieldCount"`
	CreatedAt        time.Time `json:"createdAt"`
}

type UpdateProfileInput struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type User struct {
	ID            uuid.UUID  `json:"id"`
	Email         string     `json:"email"`
	FirstName     string     `json:"firstName"`
	LastName      string     `json:"lastName"`
	Status        UserStatus `json:"status"`
	EmailVerified bool       `json:"emailVerified"`
	// Token'a yazılan etkin kiracı.
	OrganizationID uuid.UUID `json:"organizationId"`
	Permissions    []string  `json:"permissions"`
	// Silme talebinin verildiği an. Doluysa hesap geri alma penceresinde.
	DeletionRequestedAt *time.Time `json:"deletionRequestedAt,omitempty"`
	// Kalıcı silmenin planlandığı an.
	DeletionScheduledAt *time.Time `json:"deletionScheduledAt,omitempty"`
	CreatedAt           time.Time  `json:"createdAt"`
}

type VerifyEmailInput struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type VerifyEmailPayload struct {
	Verified   bool      `json:"verified"`
	VerifiedAt time.Time `json:"verifiedAt"`
}

type VerifyLoginCodeInput struct {
	Email  string       `json:"email"`
	Code   string       `json:"code"`
	Device *DeviceInput `json:"device,omitempty"`
	// Sunucunun verdiği challenge'ın cihaz özel anahtarıyla imzası (base64).
	// Kayıtlı anahtarı olan cihazlarda zorunludur.
	DeviceSignature *string `json:"deviceSignature,omitempty"`
}

type VerifyMagicLinkInput struct {
	Token           string       `json:"token"`
	Device          *DeviceInput `json:"device,omitempty"`
	DeviceSignature *string      `json:"deviceSignature,omitempty"`
}

type DevicePlatform string

const (
	DevicePlatformWindows DevicePlatform = "WINDOWS"
	DevicePlatformMacos   DevicePlatform = "MACOS"
	DevicePlatformLinux   DevicePlatform = "LINUX"
	DevicePlatformWeb     DevicePlatform = "WEB"
	DevicePlatformUnknown DevicePlatform = "UNKNOWN"
)

var AllDevicePlatform = []DevicePlatform{
	DevicePlatformWindows,
	DevicePlatformMacos,
	DevicePlatformLinux,
	DevicePlatformWeb,
	DevicePlatformUnknown,
}

func (e DevicePlatform) IsValid() bool {
	switch e {
	case DevicePlatformWindows, DevicePlatformMacos, DevicePlatformLinux, DevicePlatformWeb, DevicePlatformUnknown:
		return true
	}
	return false
}

func (e DevicePlatform) String() string {
	return string(e)
}

func (e *DevicePlatform) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DevicePlatform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DevicePlatform", str)
	}
	return nil
}

func (e DevicePlatform) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DevicePlatform) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DevicePlatform) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Difficulty string

const (
	DifficultyLow     Difficulty = "LOW"
	DifficultyMedium  Difficulty = "MEDIUM"
	DifficultyHigh    Difficulty = "HIGH"
	DifficultyExtreme Difficulty = "EXTREME"
)

var AllDifficulty = []Difficulty{
	DifficultyLow,
	DifficultyMedium,
	DifficultyHigh,
	DifficultyExtreme,
}

func (e Difficulty) IsValid() bool {
	switch e {
	case DifficultyLow, DifficultyMedium, DifficultyHigh, DifficultyExtreme:
		return true
	}
	return false
}

func (e Difficulty) String() string {
	return string(e)
}

func (e *Difficulty) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Difficulty(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Difficulty", str)
	}
	return nil
}

func (e Difficulty) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Difficulty) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Difficulty) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DocumentStatus string

const (
	// Yerinde düzenlenebilir; hiçbir oturum referans veremez.
	DocumentStatusDraft DocumentStatus = "DRAFT"
	// Donmuş ve oynanabilir.
	DocumentStatusPublished DocumentStatus = "PUBLISHED"
	// Donmuş ve yeni oturumlardan çekilmiş. Mevcut referanslar geçerli kalır.
	DocumentStatusArchived DocumentStatus = "ARCHIVED"
)

var AllDocumentStatus = []DocumentStatus{
	DocumentStatusDraft,
	DocumentStatusPublished,
	DocumentStatusArchived,
}

func (e DocumentStatus) IsValid() bool {
	switch e {
	case DocumentStatusDraft, DocumentStatusPublished, DocumentStatusArchived:
		return true
	}
	return false
}

func (e DocumentStatus) String() string {
	return string(e)
}

func (e *DocumentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentStatus", str)
	}
	return nil
}

func (e DocumentStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LLMTier string

const (
	// Her konuşma sırasında karakteri canlandırır.
	LLMTierFast LLMTier = "FAST"
	// Oturum sonunda rubriğe göre puanlar.
	LLMTierStrong LLMTier = "STRONG"
)

var AllLLMTier = []LLMTier{
	LLMTierFast,
	LLMTierStrong,
}

func (e LLMTier) IsValid() bool {
	switch e {
	case LLMTierFast, LLMTierStrong:
		return true
	}
	return false
}

func (e LLMTier) String() string {
	return string(e)
}

func (e *LLMTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LLMTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LLMTier", str)
	}
	return nil
}

func (e LLMTier) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LLMTier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LLMTier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionEventType string

const (
	SessionEventTypeTranscriptChunk SessionEventType = "TRANSCRIPT_CHUNK"
	SessionEventTypeRubricSignal    SessionEventType = "RUBRIC_SIGNAL"
	SessionEventTypeCharacterReply  SessionEventType = "CHARACTER_REPLY"
	SessionEventTypeScoringProgress SessionEventType = "SCORING_PROGRESS"
	SessionEventTypeScoreReady      SessionEventType = "SCORE_READY"
)

var AllSessionEventType = []SessionEventType{
	SessionEventTypeTranscriptChunk,
	SessionEventTypeRubricSignal,
	SessionEventTypeCharacterReply,
	SessionEventTypeScoringProgress,
	SessionEventTypeScoreReady,
}

func (e SessionEventType) IsValid() bool {
	switch e {
	case SessionEventTypeTranscriptChunk, SessionEventTypeRubricSignal, SessionEventTypeCharacterReply, SessionEventTypeScoringProgress, SessionEventTypeScoreReady:
		return true
	}
	return false
}

func (e SessionEventType) String() string {
	return string(e)
}

func (e *SessionEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionEventType", str)
	}
	return nil
}

func (e SessionEventType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusActive    SessionStatus = "ACTIVE"
	SessionStatusScoring   SessionStatus = "SCORING"
	SessionStatusCompleted SessionStatus = "COMPLETED"
	SessionStatusAbandoned SessionStatus = "ABANDONED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusActive,
	SessionStatusScoring,
	SessionStatusCompleted,
	SessionStatusAbandoned,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusActive, SessionStatusScoring, SessionStatusCompleted, SessionStatusAbandoned:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TurnRole string

const (
	TurnRoleEmployee  TurnRole = "EMPLOYEE"
	TurnRoleCharacter TurnRole = "CHARACTER"
)

var AllTurnRole = []TurnRole{
	TurnRoleEmployee,
	TurnRoleCharacter,
}

func (e TurnRole) IsValid() bool {
	switch e {
	case TurnRoleEmployee, TurnRoleCharacter:
		return true
	}
	return false
}

func (e TurnRole) String() string {
	return string(e)
}

func (e *TurnRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TurnRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TurnRole", str)
	}
	return nil
}

func (e TurnRole) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TurnRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TurnRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
	// Silme talebi verilmiş, geri alma penceresi içinde.
	UserStatusPendingDeletion UserStatus = "PENDING_DELETION"
	// Kalıcı silme işi çalışmış; kişisel veri artık yok.
	UserStatusDeleted UserStatus = "DELETED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
	UserStatusPendingDeletion,
	UserStatusDeleted,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended, UserStatusPendingDeletion, UserStatusDeleted:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
