package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric-go/masterfabric/graph/model"
	iamDTO "github.com/masterfabric-go/masterfabric/internal/application/iam/dto"
	provaModel "github.com/masterfabric-go/masterfabric/internal/domain/prova/model"
	provaRepo "github.com/masterfabric-go/masterfabric/internal/domain/prova/repository"
	domainErr "github.com/masterfabric-go/masterfabric/internal/shared/errors"
)

// RequestLoginCode is the resolver for the requestLoginCode field.
func (r *mutationResolver) RequestLoginCode(ctx context.Context, input model.RequestLoginCodeInput) (*model.RequestLoginCodePayload, error) {
	result, err := r.RequestLoginCodeUC.Execute(ctx,
		iamDTO.RequestLoginCodeRequest{Email: input.Email}, clientIP(ctx))
	if err != nil {
		return nil, err
	}
	return &model.RequestLoginCodePayload{
		Sent:               result.Sent,
		ExpiresInSeconds:   result.ExpiresInSeconds,
		ResendAfterSeconds: result.ResendAfterSeconds,
	}, nil
}

// VerifyLoginCode is the resolver for the verifyLoginCode field.
func (r *mutationResolver) VerifyLoginCode(ctx context.Context, input model.VerifyLoginCodeInput) (*model.AuthPayload, error) {
	result, err := r.VerifyLoginCodeUC.Execute(ctx, iamDTO.VerifyLoginCodeRequest{
		Email:           input.Email,
		Code:            input.Code,
		Device:          mapDeviceInput(input.Device),
		DeviceSignature: derefString(input.DeviceSignature),
	}, clientIP(ctx))
	if err != nil {
		return nil, err
	}
	return r.authPayload(ctx, result)
}

// VerifyMagicLink is the resolver for the verifyMagicLink field.
func (r *mutationResolver) VerifyMagicLink(ctx context.Context, input model.VerifyMagicLinkInput) (*model.AuthPayload, error) {
	result, err := r.VerifyMagicLinkUC.Execute(ctx, iamDTO.VerifyMagicLinkRequest{
		Token:           input.Token,
		Device:          mapDeviceInput(input.Device),
		DeviceSignature: derefString(input.DeviceSignature),
	}, clientIP(ctx))
	if err != nil {
		return nil, err
	}
	return r.authPayload(ctx, result)
}

// RequestDeviceChallenge is the resolver for the requestDeviceChallenge field.
func (r *mutationResolver) RequestDeviceChallenge(ctx context.Context, input model.DeviceChallengeInput) (*model.DeviceChallenge, error) {
	result, err := r.DeviceChallengeUC.Execute(ctx, iamDTO.DeviceChallengeRequest{
		Email:       input.Email,
		Fingerprint: input.Fingerprint,
	})
	if err != nil {
		return nil, err
	}
	return &model.DeviceChallenge{Challenge: result.Challenge, ExpiresAt: result.ExpiresAt}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthPayload, error) {
	return nil, notImplemented("refreshToken")
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	v, err := viewer(ctx)
	if err != nil {
		return false, err
	}
	if err := r.LogoutUC.Execute(ctx, v.OrgID, v.UserID, v.TokenID, v.RefreshFamilyID); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, deviceID uuid.UUID) (bool, error) {
	v, err := viewer(ctx)
	if err != nil {
		return false, err
	}
	if err := r.ManageDevicesUC.Revoke(ctx, v.OrgID, v.UserID, deviceID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCharacter is the resolver for the createCharacter field.
func (r *mutationResolver) CreateCharacter(ctx context.Context, input model.CharacterInput) (*model.Character, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	created, err := r.CharacterUC.Create(ctx, scopeOf(v), v.UserID, applyCharacterInput(input))
	if err != nil {
		return nil, err
	}
	return mapCharacter(created), nil
}

// UpdateCharacter is the resolver for the updateCharacter field.
func (r *mutationResolver) UpdateCharacter(ctx context.Context, lineageID uuid.UUID, input model.CharacterInput) (*model.Character, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	updated, err := r.CharacterUC.Update(ctx, scopeOf(v), v.UserID, lineageID, applyCharacterInput(input))
	if err != nil {
		return nil, err
	}
	return mapCharacter(updated), nil
}

// PublishCharacter is the resolver for the publishCharacter field.
func (r *mutationResolver) PublishCharacter(ctx context.Context, lineageID uuid.UUID, version int) (*model.Character, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	published, err := r.CharacterUC.Publish(ctx, scopeOf(v), v.UserID, lineageID, version)
	if err != nil {
		return nil, err
	}
	return mapCharacter(published), nil
}

// CreateScenario is the resolver for the createScenario field.
func (r *mutationResolver) CreateScenario(ctx context.Context, input model.ScenarioInput) (*model.Scenario, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	apply, err := r.applyScenarioInput(ctx, v, input)
	if err != nil {
		return nil, err
	}
	created, err := r.ScenarioUC.Create(ctx, scopeOf(v), v.UserID, apply)
	if err != nil {
		return nil, err
	}
	return mapScenario(created), nil
}

// UpdateScenario is the resolver for the updateScenario field.
func (r *mutationResolver) UpdateScenario(ctx context.Context, lineageID uuid.UUID, input model.ScenarioInput) (*model.Scenario, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	apply, err := r.applyScenarioInput(ctx, v, input)
	if err != nil {
		return nil, err
	}
	updated, err := r.ScenarioUC.Update(ctx, scopeOf(v), v.UserID, lineageID, apply)
	if err != nil {
		return nil, err
	}
	return mapScenario(updated), nil
}

// PublishScenario is the resolver for the publishScenario field.
func (r *mutationResolver) PublishScenario(ctx context.Context, lineageID uuid.UUID, version int) (*model.Scenario, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	published, err := r.ScenarioUC.Publish(ctx, scopeOf(v), v.UserID, lineageID, version)
	if err != nil {
		return nil, err
	}
	return mapScenario(published), nil
}

// CreateRubric is the resolver for the createRubric field.
func (r *mutationResolver) CreateRubric(ctx context.Context, input model.RubricInput) (*model.Rubric, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	created, err := r.RubricUC.Create(ctx, scopeOf(v), v.UserID, applyRubricInput(input))
	if err != nil {
		return nil, err
	}
	return mapRubric(created), nil
}

// UpdateRubric is the resolver for the updateRubric field.
func (r *mutationResolver) UpdateRubric(ctx context.Context, lineageID uuid.UUID, input model.RubricInput) (*model.Rubric, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	updated, err := r.RubricUC.Update(ctx, scopeOf(v), v.UserID, lineageID, applyRubricInput(input))
	if err != nil {
		return nil, err
	}
	return mapRubric(updated), nil
}

// PublishRubric is the resolver for the publishRubric field.
func (r *mutationResolver) PublishRubric(ctx context.Context, lineageID uuid.UUID, version int) (*model.Rubric, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	published, err := r.RubricUC.Publish(ctx, scopeOf(v), v.UserID, lineageID, version)
	if err != nil {
		return nil, err
	}
	return mapRubric(published), nil
}

// StartSession is the resolver for the startSession field.
func (r *mutationResolver) StartSession(ctx context.Context, input model.StartSessionInput) (*model.Session, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	session, err := r.SessionUC.Start(ctx, scopeOf(v), v.UserID, v.DeviceID, input.ScenarioLineageID)
	if err != nil {
		return nil, err
	}
	return mapSession(session), nil
}

// SubmitTurn is the resolver for the submitTurn field.
func (r *mutationResolver) SubmitTurn(ctx context.Context, input model.SubmitTurnInput) (*model.Turn, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	turn, err := r.SessionUC.SubmitTurn(ctx, scopeOf(v), v.UserID, input.SessionID, input.Text)
	if err != nil {
		return nil, err
	}
	return mapTurn(turn), nil
}

// EndSession is the resolver for the endSession field.
func (r *mutationResolver) EndSession(ctx context.Context, sessionID uuid.UUID) (*model.Session, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	session, err := r.SessionUC.End(ctx, scopeOf(v), v.UserID, sessionID)
	if err != nil {
		return nil, err
	}
	return mapSession(session), nil
}

// OverrideScore is the resolver for the overrideScore field.
func (r *mutationResolver) OverrideScore(ctx context.Context, input model.OverrideScoreInput) (*model.Score, error) {
	return nil, notImplemented("overrideScore")
}

// UpdateLLMProfile is the resolver for the updateLLMProfile field.
func (r *mutationResolver) UpdateLLMProfile(ctx context.Context, lineageID uuid.UUID, input model.LLMProfileInput) (*model.LLMProfile, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	updated, err := r.LLMProfileUC.Update(ctx, scopeOf(v), v.UserID, lineageID, toProfileSettings(input))
	if err != nil {
		return nil, err
	}
	return mapLLMProfile(updated), nil
}

// CreateLLMProfile is the resolver for the createLLMProfile field.
func (r *mutationResolver) CreateLLMProfile(ctx context.Context, input model.LLMProfileInput) (*model.LLMProfile, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	created, err := r.LLMProfileUC.Create(ctx, scopeOf(v), v.UserID, toProfileSettings(input))
	if err != nil {
		return nil, err
	}
	return mapLLMProfile(created), nil
}

// PublishLLMProfile is the resolver for the publishLLMProfile field.
func (r *mutationResolver) PublishLLMProfile(ctx context.Context, lineageID uuid.UUID, version int) (*model.LLMProfile, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	published, err := r.LLMProfileUC.Publish(ctx, scopeOf(v), v.UserID, lineageID, version)
	if err != nil {
		return nil, err
	}
	return mapLLMProfile(published), nil
}

// TestLLMProfile is the resolver for the testLLMProfile field.
func (r *mutationResolver) TestLLMProfile(ctx context.Context, input model.TestLLMProfileInput) (*model.LLMProbeResult, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	probe, err := r.LLMProfileUC.Probe(ctx, scopeOf(v), v.UserID, input.ProfileLineageID, input.Prompt)
	if err != nil {
		return nil, err
	}
	return mapProbeResult(probe), nil
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	return nil, notImplemented("updateProfile")
}

// ExportMyData is the resolver for the exportMyData field.
func (r *mutationResolver) ExportMyData(ctx context.Context) (*model.DataExport, error) {
	return nil, notImplemented("exportMyData")
}

// RequestAccountDeletion is the resolver for the requestAccountDeletion field.
func (r *mutationResolver) RequestAccountDeletion(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("requestAccountDeletion")
}

// CancelAccountDeletion is the resolver for the cancelAccountDeletion field.
func (r *mutationResolver) CancelAccountDeletion(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("cancelAccountDeletion")
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.GetByID(ctx, v.UserID)
	if err != nil {
		return nil, err
	}
	// İzinler token'daki kopyadan değil RBAC servisinden okunuyor: token
	// dakikalarca eski olabilir ve iptal edilen bir yetki hemen görünmeli.
	return mapUser(user, v.OrgID, r.permissionsOf(ctx, v.UserID, v.OrgID)), nil
}

// MyDevices is the resolver for the myDevices field.
func (r *queryResolver) MyDevices(ctx context.Context) ([]*model.Device, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	devices, err := r.ManageDevicesUC.List(ctx, v.UserID)
	if err != nil {
		return nil, err
	}
	return mapDevices(devices), nil
}

// MySessions is the resolver for the mySessions field.
func (r *queryResolver) MySessions(ctx context.Context, limit *int, offset *int) ([]*model.Session, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	sessions, err := r.SessionRepo.ListByEmployee(ctx, scopeOf(v), v.UserID, provaRepo.ListOptions{
		Limit:  clampLimit(intOrDefault(limit, 20), 20, 100),
		Offset: intOrDefault(offset, 0),
	})
	if err != nil {
		return nil, err
	}
	return mapSessions(sessions), nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id uuid.UUID) (*model.Session, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	session, err := r.SessionRepo.GetByID(ctx, scopeOf(v), id)
	if err != nil {
		return nil, err
	}
	// Sahiplik burada da kontrol ediliyor: transkript kişisel veri taşıyor ve
	// oturum kimliğini tahmin eden biri onu okuyamamalı. session:read izni
	// olan bir yönetici istisna.
	if session.EmployeeID != v.UserID {
		allowed, err := r.hasPermission(ctx, v, "session:read:all")
		if err != nil {
			return nil, err
		}
		if !allowed {
			return nil, provaModel.ErrSessionNotOwned
		}
	}
	return mapSession(session), nil
}

// Scenarios is the resolver for the scenarios field.
func (r *queryResolver) Scenarios(ctx context.Context, publishedOnly *bool) ([]*model.Scenario, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.ScenarioRepo.List(ctx, scopeOf(v), provaRepo.ListOptions{
		PublishedOnly: boolOrDefault(publishedOnly, true),
	})
	if err != nil {
		return nil, err
	}
	return mapScenarios(items), nil
}

// Scenario is the resolver for the scenario field.
func (r *queryResolver) Scenario(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Scenario, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	// Sürüm verilmezse en son yayınlanmış sürüm döner. Taslak dönmek,
	// çalışanın üzerinde çalışılan bir içeriği görmesi demek olurdu.
	if version == nil {
		item, err := r.ScenarioRepo.GetLatestPublished(ctx, scopeOf(v), lineageID)
		if err != nil {
			return nil, err
		}
		return mapScenario(item), nil
	}
	item, err := r.ScenarioRepo.GetVersion(ctx, scopeOf(v), lineageID, *version)
	if err != nil {
		return nil, err
	}
	return mapScenario(item), nil
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context, publishedOnly *bool) ([]*model.Character, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.CharacterRepo.List(ctx, scopeOf(v), provaRepo.ListOptions{
		PublishedOnly: boolOrDefault(publishedOnly, true),
	})
	if err != nil {
		return nil, err
	}
	return mapCharacters(items), nil
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Character, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	// Sürüm verilmezse en son yayınlanmış sürüm döner. Taslak dönmek,
	// çalışanın üzerinde çalışılan bir içeriği görmesi demek olurdu.
	if version == nil {
		item, err := r.CharacterRepo.GetLatestPublished(ctx, scopeOf(v), lineageID)
		if err != nil {
			return nil, err
		}
		return mapCharacter(item), nil
	}
	item, err := r.CharacterRepo.GetVersion(ctx, scopeOf(v), lineageID, *version)
	if err != nil {
		return nil, err
	}
	return mapCharacter(item), nil
}

// Rubrics is the resolver for the rubrics field.
func (r *queryResolver) Rubrics(ctx context.Context, publishedOnly *bool) ([]*model.Rubric, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	items, err := r.RubricRepo.List(ctx, scopeOf(v), provaRepo.ListOptions{
		PublishedOnly: boolOrDefault(publishedOnly, true),
	})
	if err != nil {
		return nil, err
	}
	return mapRubrics(items), nil
}

// Rubric is the resolver for the rubric field.
func (r *queryResolver) Rubric(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Rubric, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	// Sürüm verilmezse en son yayınlanmış sürüm döner. Taslak dönmek,
	// çalışanın üzerinde çalışılan bir içeriği görmesi demek olurdu.
	if version == nil {
		item, err := r.RubricRepo.GetLatestPublished(ctx, scopeOf(v), lineageID)
		if err != nil {
			return nil, err
		}
		return mapRubric(item), nil
	}
	item, err := r.RubricRepo.GetVersion(ctx, scopeOf(v), lineageID, *version)
	if err != nil {
		return nil, err
	}
	return mapRubric(item), nil
}

// LlmProfiles is the resolver for the llmProfiles field.
func (r *queryResolver) LlmProfiles(ctx context.Context) ([]*model.LLMProfile, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	profiles, err := r.LLMProfileRepo.List(ctx, scopeOf(v), provaRepo.ListOptions{})
	if err != nil {
		return nil, err
	}
	return mapLLMProfiles(profiles), nil
}

// RoutingStats is the resolver for the routingStats field.
func (r *queryResolver) RoutingStats(ctx context.Context, from *time.Time, to *time.Time) (*model.RoutingStats, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	stats, err := r.RoutingStatsUC.Execute(ctx, scopeOf(v), from, to)
	if err != nil {
		return nil, err
	}
	return mapRoutingStats(stats), nil
}

// RoutingRecords is the resolver for the routingRecords field.
func (r *queryResolver) RoutingRecords(ctx context.Context, sessionID *uuid.UUID, limit *int) ([]*model.RoutingRecord, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	records, err := r.RoutingRepo.List(ctx, scopeOf(v), sessionID, clampLimit(intOrDefault(limit, 50), 50, 500))
	if err != nil {
		return nil, err
	}
	return mapRoutingRecords(records), nil
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, limit *int, offset *int) ([]*model.AuditEntry, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	// Denetim kaydı organizasyona göre filtreleniyor. Kullanıcıya göre
	// filtrelemek yetmez: bir yönetici kendi organizasyonundaki tüm olayları
	// görebilmeli, ama başka bir kiracınınkileri asla.
	entries, _, err := r.AuditRepo.ListByOrg(ctx, v.OrgID,
		intOrDefault(offset, 0), clampLimit(intOrDefault(limit, 50), 50, 200))
	if err != nil {
		return nil, err
	}
	return mapAuditEntries(entries), nil
}

// DeletionStatus is the resolver for the deletionStatus field.
func (r *queryResolver) DeletionStatus(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("deletionStatus")
}

// Turns is the resolver for the turns field.
func (r *sessionResolver) Turns(ctx context.Context, obj *model.Session) ([]*model.Turn, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	turns, err := r.SessionRepo.ListTurns(ctx, scopeOf(v), obj.ID)
	if err != nil {
		return nil, err
	}
	return mapTurns(turns), nil
}

// Score is the resolver for the score field.
func (r *sessionResolver) Score(ctx context.Context, obj *model.Session) (*model.Score, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	score, err := r.ScoreRepo.GetBySession(ctx, scopeOf(v), obj.ID)
	if err != nil {
		// Puanı olmayan oturum bir hata değil: oturum hâlâ oynanıyor
		// olabilir. Alan nullable, ve null doğru cevap.
		if errors.Is(err, domainErr.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapScore(score), nil
}

// SessionEvents is the resolver for the sessionEvents field.
//
// Sahiplik bağlantı anında doğrulanıyor, ilk olay geldiğinde değil: transkript
// kişisel veri taşıyor ve bir oturum kimliğini tahmin eden kişi akışa hiç
// bağlanamamalı.
func (r *subscriptionResolver) SessionEvents(ctx context.Context, sessionID uuid.UUID) (<-chan *model.SessionEvent, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	session, err := r.SessionRepo.GetByID(ctx, scopeOf(v), sessionID)
	if err != nil {
		return nil, err
	}
	if session.EmployeeID != v.UserID {
		return nil, provaModel.ErrSessionNotOwned
	}

	source, unsubscribe := r.Broker.Subscribe(sessionID)
	out := make(chan *model.SessionEvent, 1)

	go func() {
		// Abonelik bağlam kapandığında sökülür. Sökülmezse yayın yolu her
		// olayı ölü bir kanala yazmayı dener ve tampon dolduğunda oturumun
		// olayları düşmeye başlar.
		defer unsubscribe()
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-source:
				if !ok {
					return
				}
				select {
				case out <- mapSessionEvent(event):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	sessionResolver      struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
