package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric-go/masterfabric/graph/model"
	iamDTO "github.com/masterfabric-go/masterfabric/internal/application/iam/dto"
)

// RequestLoginCode is the resolver for the requestLoginCode field.
func (r *mutationResolver) RequestLoginCode(ctx context.Context, input model.RequestLoginCodeInput) (*model.RequestLoginCodePayload, error) {
	result, err := r.RequestLoginCodeUC.Execute(ctx,
		iamDTO.RequestLoginCodeRequest{Email: input.Email}, clientIP(ctx))
	if err != nil {
		return nil, err
	}
	return &model.RequestLoginCodePayload{
		Sent:               result.Sent,
		ExpiresInSeconds:   result.ExpiresInSeconds,
		ResendAfterSeconds: result.ResendAfterSeconds,
	}, nil
}

// VerifyLoginCode is the resolver for the verifyLoginCode field.
func (r *mutationResolver) VerifyLoginCode(ctx context.Context, input model.VerifyLoginCodeInput) (*model.AuthPayload, error) {
	result, err := r.VerifyLoginCodeUC.Execute(ctx, iamDTO.VerifyLoginCodeRequest{
		Email:           input.Email,
		Code:            input.Code,
		Device:          mapDeviceInput(input.Device),
		DeviceSignature: derefString(input.DeviceSignature),
	}, clientIP(ctx))
	if err != nil {
		return nil, err
	}
	return r.authPayload(ctx, result)
}

// VerifyMagicLink is the resolver for the verifyMagicLink field.
func (r *mutationResolver) VerifyMagicLink(ctx context.Context, input model.VerifyMagicLinkInput) (*model.AuthPayload, error) {
	return nil, notImplemented("verifyMagicLink")
}

// RequestDeviceChallenge is the resolver for the requestDeviceChallenge field.
func (r *mutationResolver) RequestDeviceChallenge(ctx context.Context, input model.DeviceChallengeInput) (*model.DeviceChallenge, error) {
	return nil, notImplemented("requestDeviceChallenge")
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthPayload, error) {
	return nil, notImplemented("refreshToken")
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	v, err := viewer(ctx)
	if err != nil {
		return false, err
	}
	if err := r.LogoutUC.Execute(ctx, v.OrgID, v.UserID, v.TokenID, v.RefreshFamilyID); err != nil {
		return false, err
	}
	return true, nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, deviceID uuid.UUID) (bool, error) {
	v, err := viewer(ctx)
	if err != nil {
		return false, err
	}
	if err := r.ManageDevicesUC.Revoke(ctx, v.OrgID, v.UserID, deviceID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateCharacter is the resolver for the createCharacter field.
func (r *mutationResolver) CreateCharacter(ctx context.Context, input model.CharacterInput) (*model.Character, error) {
	return nil, notImplemented("createCharacter")
}

// UpdateCharacter is the resolver for the updateCharacter field.
func (r *mutationResolver) UpdateCharacter(ctx context.Context, lineageID uuid.UUID, input model.CharacterInput) (*model.Character, error) {
	return nil, notImplemented("updateCharacter")
}

// PublishCharacter is the resolver for the publishCharacter field.
func (r *mutationResolver) PublishCharacter(ctx context.Context, lineageID uuid.UUID, version int) (*model.Character, error) {
	return nil, notImplemented("publishCharacter")
}

// CreateScenario is the resolver for the createScenario field.
func (r *mutationResolver) CreateScenario(ctx context.Context, input model.ScenarioInput) (*model.Scenario, error) {
	return nil, notImplemented("createScenario")
}

// UpdateScenario is the resolver for the updateScenario field.
func (r *mutationResolver) UpdateScenario(ctx context.Context, lineageID uuid.UUID, input model.ScenarioInput) (*model.Scenario, error) {
	return nil, notImplemented("updateScenario")
}

// PublishScenario is the resolver for the publishScenario field.
func (r *mutationResolver) PublishScenario(ctx context.Context, lineageID uuid.UUID, version int) (*model.Scenario, error) {
	return nil, notImplemented("publishScenario")
}

// CreateRubric is the resolver for the createRubric field.
func (r *mutationResolver) CreateRubric(ctx context.Context, input model.RubricInput) (*model.Rubric, error) {
	return nil, notImplemented("createRubric")
}

// UpdateRubric is the resolver for the updateRubric field.
func (r *mutationResolver) UpdateRubric(ctx context.Context, lineageID uuid.UUID, input model.RubricInput) (*model.Rubric, error) {
	return nil, notImplemented("updateRubric")
}

// PublishRubric is the resolver for the publishRubric field.
func (r *mutationResolver) PublishRubric(ctx context.Context, lineageID uuid.UUID, version int) (*model.Rubric, error) {
	return nil, notImplemented("publishRubric")
}

// StartSession is the resolver for the startSession field.
func (r *mutationResolver) StartSession(ctx context.Context, input model.StartSessionInput) (*model.Session, error) {
	return nil, notImplemented("startSession")
}

// SubmitTurn is the resolver for the submitTurn field.
func (r *mutationResolver) SubmitTurn(ctx context.Context, input model.SubmitTurnInput) (*model.Turn, error) {
	return nil, notImplemented("submitTurn")
}

// EndSession is the resolver for the endSession field.
func (r *mutationResolver) EndSession(ctx context.Context, sessionID uuid.UUID) (*model.Session, error) {
	return nil, notImplemented("endSession")
}

// OverrideScore is the resolver for the overrideScore field.
func (r *mutationResolver) OverrideScore(ctx context.Context, input model.OverrideScoreInput) (*model.Score, error) {
	return nil, notImplemented("overrideScore")
}

// UpdateLLMProfile is the resolver for the updateLLMProfile field.
func (r *mutationResolver) UpdateLLMProfile(ctx context.Context, lineageID uuid.UUID, input model.LLMProfileInput) (*model.LLMProfile, error) {
	return nil, notImplemented("updateLLMProfile")
}

// CreateLLMProfile is the resolver for the createLLMProfile field.
func (r *mutationResolver) CreateLLMProfile(ctx context.Context, input model.LLMProfileInput) (*model.LLMProfile, error) {
	return nil, notImplemented("createLLMProfile")
}

// PublishLLMProfile is the resolver for the publishLLMProfile field.
func (r *mutationResolver) PublishLLMProfile(ctx context.Context, lineageID uuid.UUID, version int) (*model.LLMProfile, error) {
	return nil, notImplemented("publishLLMProfile")
}

// TestLLMProfile is the resolver for the testLLMProfile field.
func (r *mutationResolver) TestLLMProfile(ctx context.Context, input model.TestLLMProfileInput) (*model.LLMProbeResult, error) {
	return nil, notImplemented("testLLMProfile")
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	return nil, notImplemented("updateProfile")
}

// ExportMyData is the resolver for the exportMyData field.
func (r *mutationResolver) ExportMyData(ctx context.Context) (*model.DataExport, error) {
	return nil, notImplemented("exportMyData")
}

// RequestAccountDeletion is the resolver for the requestAccountDeletion field.
func (r *mutationResolver) RequestAccountDeletion(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("requestAccountDeletion")
}

// CancelAccountDeletion is the resolver for the cancelAccountDeletion field.
func (r *mutationResolver) CancelAccountDeletion(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("cancelAccountDeletion")
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Users.GetByID(ctx, v.UserID)
	if err != nil {
		return nil, err
	}
	// İzinler token'daki kopyadan değil RBAC servisinden okunuyor: token
	// dakikalarca eski olabilir ve iptal edilen bir yetki hemen görünmeli.
	return mapUser(user, v.OrgID, r.permissionsOf(ctx, v.UserID, v.OrgID)), nil
}

// MyDevices is the resolver for the myDevices field.
func (r *queryResolver) MyDevices(ctx context.Context) ([]*model.Device, error) {
	v, err := viewer(ctx)
	if err != nil {
		return nil, err
	}
	devices, err := r.ManageDevicesUC.List(ctx, v.UserID)
	if err != nil {
		return nil, err
	}
	return mapDevices(devices), nil
}

// MySessions is the resolver for the mySessions field.
func (r *queryResolver) MySessions(ctx context.Context, limit *int, offset *int) ([]*model.Session, error) {
	return nil, notImplemented("mySessions")
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id uuid.UUID) (*model.Session, error) {
	return nil, notImplemented("session")
}

// Scenarios is the resolver for the scenarios field.
func (r *queryResolver) Scenarios(ctx context.Context, publishedOnly *bool) ([]*model.Scenario, error) {
	return nil, notImplemented("scenarios")
}

// Scenario is the resolver for the scenario field.
func (r *queryResolver) Scenario(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Scenario, error) {
	return nil, notImplemented("scenario")
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context, publishedOnly *bool) ([]*model.Character, error) {
	return nil, notImplemented("characters")
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Character, error) {
	return nil, notImplemented("character")
}

// Rubrics is the resolver for the rubrics field.
func (r *queryResolver) Rubrics(ctx context.Context, publishedOnly *bool) ([]*model.Rubric, error) {
	return nil, notImplemented("rubrics")
}

// Rubric is the resolver for the rubric field.
func (r *queryResolver) Rubric(ctx context.Context, lineageID uuid.UUID, version *int) (*model.Rubric, error) {
	return nil, notImplemented("rubric")
}

// LlmProfiles is the resolver for the llmProfiles field.
func (r *queryResolver) LlmProfiles(ctx context.Context) ([]*model.LLMProfile, error) {
	return nil, notImplemented("llmProfiles")
}

// RoutingStats is the resolver for the routingStats field.
func (r *queryResolver) RoutingStats(ctx context.Context, from *time.Time, to *time.Time) (*model.RoutingStats, error) {
	return nil, notImplemented("routingStats")
}

// RoutingRecords is the resolver for the routingRecords field.
func (r *queryResolver) RoutingRecords(ctx context.Context, sessionID *uuid.UUID, limit *int) ([]*model.RoutingRecord, error) {
	return nil, notImplemented("routingRecords")
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, limit *int, offset *int) ([]*model.AuditEntry, error) {
	return nil, notImplemented("auditLog")
}

// DeletionStatus is the resolver for the deletionStatus field.
func (r *queryResolver) DeletionStatus(ctx context.Context) (*model.DeletionStatus, error) {
	return nil, notImplemented("deletionStatus")
}

// SessionEvents is the resolver for the sessionEvents field.
func (r *subscriptionResolver) SessionEvents(ctx context.Context, sessionID uuid.UUID) (<-chan *model.SessionEvent, error) {
	return nil, notImplemented("sessionEvents")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
